name: Auto Api E5

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 9,13,16 * * 1-5"
  watch:
    types: [started]

jobs:
  auto:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Test Api
      env:
        ID: ${{ secrets.APP_ID }}
        SECRET: ${{ secrets.APP_SECRET }}
      run: |
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python3 auto.py -i $ID -s $SECRET
    # 上传新的 refresh_token 到仓库
    - name: Commit New Refresh Token
      run: |
        git pull
        git config --global user.email xxxxxxxxxx@xxxxxxx.com
        git config --global user.name xxxxxx
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        github_token: $TOKEN
        branch: main
